//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.TlsRpt.Poller.Domain.Errors.Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TlsRptParserMarkDown {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TlsRptParserMarkDown() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.TlsRpt.Poller.Domain.Errors.Parser.TlsRptParserMarkDown", typeof(TlsRptParserMarkDown).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLS aggregate reports can be delivered using either email or HTTPS.
        ///
        ///Email example:
        ///_smtp._tls.example.com. IN TXT \
        ///&quot;v=TLSRPTv1;rua=mailto:reports@example.com&quot;
        ///      
        ///HTTPS example:
        ///_smtp._tls.example.com. IN TXT \
        ///&quot;v=TLSRPTv1; \
        ///rua=https://reporting.example.com/v1/tlsrpt&quot;
        ///    .
        /// </summary>
        internal static string MalformedUriError {
            get {
                return ResourceManager.GetString("MalformedUriError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This TLS/RPT record is using an unsupported method of delivering TLS aggregate reports. Only mailto or https are valid.
        ///
        ///It&apos;s most likely that mailto or https has a spelling mistake, please investigate..
        /// </summary>
        internal static string UnknownUriError {
            get {
                return ResourceManager.GetString("UnknownUriError", resourceCulture);
            }
        }
    }
}
