//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MailCheck.TlsRpt.Poller.Domain.Errors.Parser {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class TlsRptParserErrorMessages {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TlsRptParserErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MailCheck.TlsRpt.Poller.Domain.Errors.Parser.TlsRptParserErrorMessages", typeof(TlsRptParserErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} value: {1}..
        /// </summary>
        internal static string InvalidItemValueError {
            get {
                return ResourceManager.GetString("InvalidItemValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version. TlsRpt record must start with v=TLSRPTv1..
        /// </summary>
        internal static string InvalidVersionValueError {
            get {
                return ResourceManager.GetString("InvalidVersionValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed {0} {1}.
        /// </summary>
        internal static string MalformedItemError {
            get {
                return ResourceManager.GetString("MalformedItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} tagKey should occur no more than {1}. This record has at least {2} occurrences..
        /// </summary>
        internal static string MaxOccurrencesExceededError {
            get {
                return ResourceManager.GetString("MaxOccurrencesExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown {0} {1} with value {2}..
        /// </summary>
        internal static string UnknownItemError {
            get {
                return ResourceManager.GetString("UnknownItemError", resourceCulture);
            }
        }
    }
}
